name: ConfigurablePlaceholders
version: '${project.version}'
main: org.lushplugins.configurableplaceholders.ConfigurablePlaceholders
api-version: '1.20'
github-repo: OakLoaf/ConfigurablePlaceholders
depend:
  - floodgate
  - PlaceholderAPI