name: ConfigurablePlaceholders
version: '${version}'
main: me.dave.configurableplaceholders.ConfigurablePlaceholders
api-version: '1.20'
depend:
  - floodgate
  - PlaceholderAPI
commands:
  configurableplaceholders:
    aliases:
      - cplaceholders
    description: Main ConfigurablePlaceholders command
    usage: /configurableplaceholders